# Generated by Django 5.2.6 on 2025-09-27 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0003_seed_initial_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.UniqueConstraint(
                fields=("form", "name"), name="unique_form_field_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="formsubmission",
            constraint=models.UniqueConstraint(
                fields=("form", "submitted_by", "form_version"),
                name="unique_submission_per_user_per_version",
            ),
        ),
    ]
