name: CI - Backend & Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: dynamicform
          POSTGRES_USER: dfuser
          POSTGRES_PASSWORD: dfuser
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U dfuser -d dynamicform"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # Django test settings
      DATABASE_NAME: dynamicform
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DJANGO_SECRET_KEY: testsecret
      DEBUG: "False"

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Backend ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Django migrations
        run: |
          cd backend
          python manage.py migrate --noinput

      - name: Run backend tests
        run: |
          cd backend
          pytest --disable-warnings -q

      # ---------- Frontend ----------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build
